layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: minhluan2292
  hackerrank: minhluan2292
  instagram: minhluan2292
  # keybase: your_username
  linkedin: minhluan2292
  # mastodon: your_username
  # medium: nhoxbypass
  stackoverflow: 13150367
  # telegram: your_username
  twitter: minhluan2292
  # unsplash: your_username
  # vk: your_username
  # website: 
  # youtube: your_username
  codingame: 1cfc4110954224b433ce48200ca1bf345162683

topics:
  - name: Laravel
    web_url: https://laravel.com/
    image_url: https://laravel.com/img/logomark.min.svg

  - name: VueJS
    web_url: https://vuejs.org/
    image_url: https://vuejs.org/images/logo.png

  - name: React
    web_url: https://reactjs.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg
